---
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
      - id: requirements-txt-fixer

  - repo: https://github.com/codespell-project/codespell.git
    rev: v2.1.0
    hooks:
      - id: codespell
        args: [-w]
        files: ^.*\.(md|py|jinja|yaml|yml|sh|feature)$

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    # Otherwise will fail on commit-msg hook
    hooks:
      - id: prettier
        stages: [commit]
        exclude: Pipfile.lock

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--skip-glob", "/builds/*"]

  # Python code formatting
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  # Python code formatting in code blocks inside docs
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==22.3.0]

  # Run tests suite with Pytest
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        stages: [commit]
        types: [python]
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true

  # Validate Poetry
  - repo: https://github.com/python-poetry/poetry
    rev: "1.8.2" # add version here
    hooks:
      - id: poetry-check
      - id: poetry-lock
