[project]
name = "infraboard"
version = "0.1.0"
description = "Local dashboard for monitoring system performance"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.8",
    "psutil>=7.2.2",
    "streamlit>=1.55.0",
]

[dependency-groups]
dev = [
    "black>=26.3.1",
    "coverage>=7.13.5",
    "flake8>=7.3.0",
    "mypy>=1.19.1",
    "pre-commit>=4.5.1",
    "pylint>=4.0.5",
    "pytest>=9.0.2",
    "selenium>=4.41.0",
]
