# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: Testing CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: ./.github/actions/setup-python-base
        with:
          for-testing: true
          python-version: ${{ matrix.python-version }}
      - name: Install Just
        uses: extractions/setup-just@v2
      - name: Run Pytest with coverage
        run: |
          just coverage
